# Generated by Django 3.2.4 on 2024-07-03 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_merchant',
            field=models.BooleanField(default=False),
        ),
    ]
